networks:
    192.168.5.0/24:
        # Authoritative:
        # When the DHCP server is configured as authoritative, the server will respond with
        # ACK or NACK as appropriate for all the received REQUEST and INFORM messages
        # belonging to the subnet. If non-authoritative, INFORM will be ignored on this network
        #
        # authoritative: true
        #
        # `ping_check` (default false) set to true will ping before assigning an IP
        #
        # ping_check: false
        #
        # adjust the default ping timeout (default: 500ms)
        #
        # ping_timeout_ms: 500
        #
        # Decline & Duplicate Address Detection:
        # `probation_period` (seconds) is defined per-network. If any DHCP messages are received from
        # this network with a message type of DECLINE, or if a ping check is successful
        # (meaning the address is in use), dora will not attempt to lease the IP inside of
        # the probation period.
        #
        probation_period: 86400
        # (optional)
        # `server_id` _must_ be an IP that dora is reachable on.
        # OR IF IT IS NOT specified, dora will use the IP of the interface we recv'd the message on.
        # OR we will just use the first non-loopback interface IP
        server_id: 192.168.5.1
        # (optional) this will replace the `sname` field in the DHCP header
        # server_name: "example.org"
        #
        # (optional) this will replace the `fname` field in the DHCP header
        # file_name: "bootfile.efi"
        ranges:
            -
                # (optional) specifies the class name that must have been matched on
                class: "my_class"
                # start of your range
                start: 192.168.5.2
                # end of your range
                end: 192.168.5.250
                # configured lease time (only `default` is required)
                config:
                    lease_time:
                        default: 3600
                        min: 1200
                        max: 4800
                # Both reservations & ranges can include an options map, if an incoming dhcp msg gets
                # an IP from that reservation or range, it will also use the corresponding `options`
                # to respond to any parameter request list values.
                options:
                    values:
                        # each option has a `type`/`value`. the 'value' field can implicitly be a list (all types except b64/hex/sub_option).
                        # valid types are:
                        #   ip          ex. 1.2.3.4 or [1.2.3.4, 1.2.3.4]
                        #   domain      (encodes list of domains in compressed DNS format) ex. ["foobar.com.", "apple.marketing.com."] or a single domain ex. "foobar.com."
                        #   str         ex. "foobar" or ["foo", "bar"]
                        #   u8          ex. 1 or [1, 2, 3]
                        #   u16         ex. 1 or [1, 2, 3]
                        #   u32         ex. 1 or [1, 2, 3]
                        #   i32         ex. -1 or [-1, 2, 3]
                        #   b64         ex. "Zm9vYmFy"
                        #   hex         ex. "DEADBEEF"
                        #   sub_option
                        # Look at: https://docs.rs/dhcproto/latest/dhcproto/v4/enum.DhcpOption.html for available opts and their corresponding type.
                        #
                        # For specifying options, use the number code or the name, for example
                        #   1:
                        #       type: ip
                        #       value: 255.255.255.0
                        # is equivalent to
                        #   subnet_mask:
                        #       type: ip
                        #       value: 255.255.255.0
                        # only some options have support for the string name identifier.
                        1: # subnet mask (if not specified, comes from `interfaces`)
                            type: ip
                            value: 255.255.255.0
                        3: # router (if not specified, will come from `interfaces`)
                            type: ip
                            value:
                                - 192.168.5.1
                        6: # domain name (if running a DNS server like dnsmasq also, use its IP)
                            type: ip
                            value:
                                - 8.8.8.8
                        28: # broadcast addr (if not specified, comes from `interfaces`)
                           type: ip
                           value: 192.168.5.255
                # you can add exceptions each range
                #
                # except:
                #     - 192.168.0.123
                #     - 192.168.0.124
